### ISSUE TITLE
Icons are missing

### ISSUE THREAD

**Issue by Rudiiini** [app-generator/django-material-wpx-pro#1]
Hi,

I bought material pro and everything works fine, but I can't see the icons.

Thank you, Rudi
![Icons](https://user-images.githubusercontent.com/73608093/97618784-c36de680-1a1f-11eb-80bd-ecb74c21b229.PNG)

**Comment by app-generator** [comment]
Hello @Rudiiini 
Can you provide more information regarding your environment? 
OS information mostly: version, 32/64

Thank you!

**Comment by Rudiiini** [comment]
Hi,

I use a Win 10 Pro 64 Bit (Version 1909). Just let me know, if you need more information.

Then I start the server I get this warning. Maybe this causes the issues with the missing icons.

_System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace_

Thank you.
Rudi

Edit: I just installed and tested the dashboard on an unbuntu system. I face the exact issue. I get the warning then I start the server and the icons are missing all over the dashboard. Not only on the icons page, also in the sidebar. It looks on my ubuntu system exactly like in my screenshot from my windows system.

**Comment by app-generator** [comment]
- Fonts issue patched in [commit](https://github.com/app-generator/priv-django-material-dashboard-wpx-pro/commit/ab74a0a81b8ecebfafc5321d3aed174996a12f54)
- Routing issues patched in [commit](https://github.com/app-generator/priv-django-material-dashboard-wpx-pro/commit/dc7d8e0201de4b81c296cd45693312838afc0f4c)

Please update.

**Comment by Rudiiini** [comment]
Works great, thanks for the support. 👍
